# Generated by Django 4.2.1 on 2023-06-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
