# Generated by Django 4.2.1 on 2023-06-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.unit'),
            preserve_default=False,
        ),
    ]
