# Generated by Django 4.2.1 on 2023-06-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_unit_images_image_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='unit',
            name='governorate',
            field=models.TextField(blank=True, null=True, verbose_name='governorate'),
        ),
    ]
