# Generated by Django 4.2.1 on 2023-06-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_unit_city_unit_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='is_approved'),
        ),
    ]
