# Generated by Django 4.2.1 on 2023-06-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_unit_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='images',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
